### ISSUE TITLE
library_test.py issue

### ISSUE THREAD

**Issue by Alf71** [AlexanderKud/Secp256k1_PythonLibrary#2]
KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU75NBY2dKG
True
Traceback (most recent call last):
  File "/mnt/v/GITHUB/AlexCurl/Secp256k1_PythonLibrary-main/Secp256k1_PythonLibrary-main/library_test.py", line 95, in <module>
    pk1 = secp256k1.wif_to_privatekey("5K2jRkYtEju8Ds2Y3HwwNBut1a6vADjy6B4Eu5N8NZbkiaZ5DTZ")
  File "/mnt/v/GITHUB/AlexCurl/Secp256k1_PythonLibrary-main/Secp256k1_PythonLibrary-main/secp256k1.py", line 217, in wif_to_privatekey
    return int.from_bytes(res)
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)

Open secp256k1.py.

Locate the wif_to_privatekey function (around line 217).

Change the line:
python

return int.from_bytes(res)

to:
python

return int.from_bytes(res, 'big')

**Comment by AlexanderKud** [comment]
Done. If you find other bugs or have code performance improvement proposals let know.

**Comment by Alf71** [comment]
Well, you still have some good ideas...  ; )

https://github.com/iceland2k14/secp256k1/blob/main/secp256k1.py

https://github.com/Mizogg/iceland2k14-secp256k1

**Comment by AlexanderKud** [comment]
Do not quite get your point. Explain.

**Comment by Alf71** [comment]
Well, I was wishing to understand how icelands library works and you have shown the way again.
And I see that you are constantly implementing yours day by day

**Comment by AlexanderKud** [comment]
I see now. Well I do not know exactly how he implemented his library but it has the same codebase (VanitySearch, KeyHunt-Cuda + some extra functions). I will publish my research Bitcoin Webserver again powered by my implementation of the library.
